language: python
addons:
  apt:
    packages:
    - g++
    - python-dev
cache:
  directories:
  - build
  - $HOME/.cache/pip
python:
  - 2.7
sudo: false
install:
  - source ./install_dependencies.sh
before_script:
  - pip install codecov
script:
  - coverage run setup.py test
after_success:
  - codecov